// <auto-generated />
using System;
using Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Domain.Migrations
{
    [DbContext(typeof(ReportContext))]
    partial class ReportContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.9");

            modelBuilder.Entity("Domain.Models.DataCore.Conjoiner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Conjoiner");
                });

            modelBuilder.Entity("Domain.Models.DataCore.FieldType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FieldType");
                });

            modelBuilder.Entity("Domain.Models.DataCore.Operator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Operator");
                });

            modelBuilder.Entity("Domain.Models.DataSets.DataSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DataSet");
                });

            modelBuilder.Entity("Domain.Models.DataSets.Field", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DataSetId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FieldTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DataSetId");

                    b.HasIndex("FieldTypeId");

                    b.ToTable("Field");
                });

            modelBuilder.Entity("Domain.Models.Queries.Conjunction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConjoinerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatementId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ConjoinerId");

                    b.HasIndex("StatementId");

                    b.ToTable("Conjunction");
                });

            modelBuilder.Entity("Domain.Models.Queries.Criterion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FieldId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OperatorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatementId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FieldId");

                    b.HasIndex("OperatorId");

                    b.HasIndex("StatementId");

                    b.ToTable("Criterion");
                });

            modelBuilder.Entity("Domain.Models.Queries.CriterionValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CriterionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CriterionId");

                    b.ToTable("CriterionValue");
                });

            modelBuilder.Entity("Domain.Models.Queries.Query", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DataSetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StatementId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DataSetId");

                    b.HasIndex("StatementId");

                    b.ToTable("Query");
                });

            modelBuilder.Entity("Domain.Models.Queries.Statement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ConjunctionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ConjunctionId");

                    b.ToTable("Statement");
                });

            modelBuilder.Entity("FieldQuery", b =>
                {
                    b.Property<int>("FieldsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QueriesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FieldsId", "QueriesId");

                    b.HasIndex("QueriesId");

                    b.ToTable("FieldQuery");
                });

            modelBuilder.Entity("FieldTypeOperator", b =>
                {
                    b.Property<int>("FieldTypesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OperatorsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FieldTypesId", "OperatorsId");

                    b.HasIndex("OperatorsId");

                    b.ToTable("FieldTypeOperator");
                });

            modelBuilder.Entity("Domain.Models.DataSets.Field", b =>
                {
                    b.HasOne("Domain.Models.DataSets.DataSet", "DataSet")
                        .WithMany("Fields")
                        .HasForeignKey("DataSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.DataCore.FieldType", "FieldType")
                        .WithMany()
                        .HasForeignKey("FieldTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataSet");

                    b.Navigation("FieldType");
                });

            modelBuilder.Entity("Domain.Models.Queries.Conjunction", b =>
                {
                    b.HasOne("Domain.Models.DataCore.Conjoiner", "Conjoiner")
                        .WithMany()
                        .HasForeignKey("ConjoinerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Queries.Statement", "Statement")
                        .WithMany("Conjunctions")
                        .HasForeignKey("StatementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conjoiner");

                    b.Navigation("Statement");
                });

            modelBuilder.Entity("Domain.Models.Queries.Criterion", b =>
                {
                    b.HasOne("Domain.Models.DataSets.Field", "Field")
                        .WithMany()
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.DataCore.Operator", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Queries.Statement", "Statement")
                        .WithMany("Criterions")
                        .HasForeignKey("StatementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Field");

                    b.Navigation("Operator");

                    b.Navigation("Statement");
                });

            modelBuilder.Entity("Domain.Models.Queries.CriterionValue", b =>
                {
                    b.HasOne("Domain.Models.Queries.Criterion", "Criterion")
                        .WithMany("CriterionValues")
                        .HasForeignKey("CriterionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Criterion");
                });

            modelBuilder.Entity("Domain.Models.Queries.Query", b =>
                {
                    b.HasOne("Domain.Models.DataSets.DataSet", "DataSet")
                        .WithMany()
                        .HasForeignKey("DataSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Queries.Statement", "Statement")
                        .WithMany()
                        .HasForeignKey("StatementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataSet");

                    b.Navigation("Statement");
                });

            modelBuilder.Entity("Domain.Models.Queries.Statement", b =>
                {
                    b.HasOne("Domain.Models.Queries.Conjunction", "Conjunction")
                        .WithMany("Statements")
                        .HasForeignKey("ConjunctionId");

                    b.Navigation("Conjunction");
                });

            modelBuilder.Entity("FieldQuery", b =>
                {
                    b.HasOne("Domain.Models.DataSets.Field", null)
                        .WithMany()
                        .HasForeignKey("FieldsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Queries.Query", null)
                        .WithMany()
                        .HasForeignKey("QueriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FieldTypeOperator", b =>
                {
                    b.HasOne("Domain.Models.DataCore.FieldType", null)
                        .WithMany()
                        .HasForeignKey("FieldTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.DataCore.Operator", null)
                        .WithMany()
                        .HasForeignKey("OperatorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.DataSets.DataSet", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("Domain.Models.Queries.Conjunction", b =>
                {
                    b.Navigation("Statements");
                });

            modelBuilder.Entity("Domain.Models.Queries.Criterion", b =>
                {
                    b.Navigation("CriterionValues");
                });

            modelBuilder.Entity("Domain.Models.Queries.Statement", b =>
                {
                    b.Navigation("Conjunctions");

                    b.Navigation("Criterions");
                });
#pragma warning restore 612, 618
        }
    }
}
