// <auto-generated />
using System;
using Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Domain.Migrations
{
    [DbContext(typeof(ReportContext))]
    partial class ReportContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.9");

            modelBuilder.Entity("Domain.Models.DataCore.Conjoiner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Conjoiner");
                });

            modelBuilder.Entity("Domain.Models.DataCore.Operator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExecutionString")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Operator");
                });

            modelBuilder.Entity("Domain.Models.DataCore.OperatorFieldType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DbType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OperatorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OperatorId");

                    b.ToTable("OperatorFieldTypes");
                });

            modelBuilder.Entity("Domain.Models.DataCore.Parameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DbType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OperatorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OperatorId");

                    b.ToTable("Parameters");
                });

            modelBuilder.Entity("Domain.Models.FieldSets.Field", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DbType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FieldSetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FieldSetId");

                    b.ToTable("Field");
                });

            modelBuilder.Entity("Domain.Models.FieldSets.FieldSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FieldSet");
                });

            modelBuilder.Entity("Domain.Models.Queries.Conjunction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConjoinerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatementId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ConjoinerId");

                    b.HasIndex("StatementId");

                    b.ToTable("Conjunction");
                });

            modelBuilder.Entity("Domain.Models.Queries.Criterion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FieldId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OperatorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatementId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FieldId");

                    b.HasIndex("OperatorId");

                    b.HasIndex("StatementId");

                    b.ToTable("Criterion");
                });

            modelBuilder.Entity("Domain.Models.Queries.CriterionParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CriterionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParameterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CriterionId");

                    b.HasIndex("ParameterId");

                    b.ToTable("CriterionValue");
                });

            modelBuilder.Entity("Domain.Models.Queries.Query", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FieldSetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StatementId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FieldSetId");

                    b.HasIndex("StatementId");

                    b.ToTable("Query");
                });

            modelBuilder.Entity("Domain.Models.Queries.Statement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ConjunctionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ConjunctionId");

                    b.ToTable("Statement");
                });

            modelBuilder.Entity("FieldQuery", b =>
                {
                    b.Property<int>("FieldsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QueriesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FieldsId", "QueriesId");

                    b.HasIndex("QueriesId");

                    b.ToTable("FieldQuery");
                });

            modelBuilder.Entity("Domain.Models.DataCore.OperatorFieldType", b =>
                {
                    b.HasOne("Domain.Models.DataCore.Operator", "Operator")
                        .WithMany("OperatorFieldTypes")
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("Domain.Models.DataCore.Parameter", b =>
                {
                    b.HasOne("Domain.Models.DataCore.Operator", "Operator")
                        .WithMany("Parameters")
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("Domain.Models.FieldSets.Field", b =>
                {
                    b.HasOne("Domain.Models.FieldSets.FieldSet", "FieldSet")
                        .WithMany("Fields")
                        .HasForeignKey("FieldSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FieldSet");
                });

            modelBuilder.Entity("Domain.Models.Queries.Conjunction", b =>
                {
                    b.HasOne("Domain.Models.DataCore.Conjoiner", "Conjoiner")
                        .WithMany()
                        .HasForeignKey("ConjoinerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Queries.Statement", "Statement")
                        .WithMany("Conjunctions")
                        .HasForeignKey("StatementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conjoiner");

                    b.Navigation("Statement");
                });

            modelBuilder.Entity("Domain.Models.Queries.Criterion", b =>
                {
                    b.HasOne("Domain.Models.FieldSets.Field", "Field")
                        .WithMany()
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.DataCore.Operator", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Queries.Statement", "Statement")
                        .WithMany("Criterions")
                        .HasForeignKey("StatementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Field");

                    b.Navigation("Operator");

                    b.Navigation("Statement");
                });

            modelBuilder.Entity("Domain.Models.Queries.CriterionParameter", b =>
                {
                    b.HasOne("Domain.Models.Queries.Criterion", "Criterion")
                        .WithMany("CriterionParameters")
                        .HasForeignKey("CriterionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.DataCore.Parameter", "Parameter")
                        .WithMany()
                        .HasForeignKey("ParameterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Criterion");

                    b.Navigation("Parameter");
                });

            modelBuilder.Entity("Domain.Models.Queries.Query", b =>
                {
                    b.HasOne("Domain.Models.FieldSets.FieldSet", "FieldSet")
                        .WithMany()
                        .HasForeignKey("FieldSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Queries.Statement", "Statement")
                        .WithMany()
                        .HasForeignKey("StatementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FieldSet");

                    b.Navigation("Statement");
                });

            modelBuilder.Entity("Domain.Models.Queries.Statement", b =>
                {
                    b.HasOne("Domain.Models.Queries.Conjunction", "Conjunction")
                        .WithMany("Statements")
                        .HasForeignKey("ConjunctionId");

                    b.Navigation("Conjunction");
                });

            modelBuilder.Entity("FieldQuery", b =>
                {
                    b.HasOne("Domain.Models.FieldSets.Field", null)
                        .WithMany()
                        .HasForeignKey("FieldsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Queries.Query", null)
                        .WithMany()
                        .HasForeignKey("QueriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Models.DataCore.Operator", b =>
                {
                    b.Navigation("OperatorFieldTypes");

                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("Domain.Models.FieldSets.FieldSet", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("Domain.Models.Queries.Conjunction", b =>
                {
                    b.Navigation("Statements");
                });

            modelBuilder.Entity("Domain.Models.Queries.Criterion", b =>
                {
                    b.Navigation("CriterionParameters");
                });

            modelBuilder.Entity("Domain.Models.Queries.Statement", b =>
                {
                    b.Navigation("Conjunctions");

                    b.Navigation("Criterions");
                });
#pragma warning restore 612, 618
        }
    }
}
